version: 2.1

executors:
  node9:
    docker:
      - image: circleci/node:9
  node12:
    docker:
      - image: circleci/node:12
  php7:
    docker:
      - image: circleci/php:7.2.17-node

commands:
  build_project:
    description: "Building << path >>..."
    parameters:
      path:
        type: string
        default: ""
    steps:
      - run:
          name: "Building << parameters.path >>"
          command: |
            cd "<< parameters.path >>"
            yarn
            yarn build
            yarn lint

  deploy_project:
    description: "Deploying << path >>..."
    parameters:
      path:
        type: string
        default: ""
      app_name:
        type: string
        default: ""
    steps:
      - run:
          name: "Deploying << parameters.path >>"
          command: |
            git subtree push --prefix << parameters.path >> https://heroku:$HEROKU_API_KEY@git.heroku.com/<< parameters.app_name >>.git master

jobs:
  build_dynamic_rendering:
    executor: node9
    steps:
      - checkout
      - build_project:
          path: "dynamic-rendering/instantsearch.js"

  deploy_dynamic_rendering:
    executor: node9
    steps:
      - checkout
      - deploy_project:
          path: "dynamic-rendering/instantsearch.js"
          app_name: "is-seo-dynamic-routing-0b"

  build_server_side_rendering:
    executor: node12
    resource_class: xlarge
    steps:
      - checkout
      - build_project:
          path: "server-side-rendering/react-instantsearch"

  deploy_server_side_rendering:
    executor: node12
    resource_class: xlarge
    steps:
      - checkout
      - deploy_project:
          path: "server-side-rendering/react-instantsearch"
          app_name: "is-seo-ssr-react-0"

  build_partial_server_side_rendering:
    executor: php7
    steps:
      - checkout
      - build_project:
          path: "partial-server-side-rendering/react-instantsearch"

  deploy_partial_server_side_rendering:
    executor: php7
    steps:
      - checkout
      - deploy_project:
          path: "partial-server-side-rendering/react-instantsearch"
          app_name: "is-seo-pssr-react-0"

  build_client_side_rendering_js:
    executor: node9
    steps:
      - checkout
      - build_project:
          path: "client-side-rendering/instantsearch.js"

  deploy_client_side_rendering_js:
    executor: node9
    steps:
      - checkout
      - deploy_project:
          path: "client-side-rendering/instantsearch.js"
          app_name: "is-seo-csr-js-0"

  build_client_side_rendering_react:
    executor: node9
    steps:
      - checkout
      - build_project:
          path: "client-side-rendering/react-instantsearch"

  deploy_client_side_rendering_react:
    executor: node9
    steps:
      - checkout
      - deploy_project:
          path: "client-side-rendering/react-instantsearch"
          app_name: "is-seo-csr-react-0"

  build_client_side_rendering_angular:
    executor: node9
    steps:
      - checkout
      - build_project:
          path: "client-side-rendering/angular-instantsearch"

  deploy_client_side_rendering_angular:
    executor: node9
    steps:
      - checkout
      - deploy_project:
          path: "client-side-rendering/angular-instantsearch"
          app_name: "is-seo-csr-angular-0"

  build_client_side_rendering_vue:
    executor: node9
    steps:
      - checkout
      - build_project:
          path: "client-side-rendering/vue-instantsearch"

  deploy_client_side_rendering_vue:
    executor: node9
    steps:
      - checkout
      - deploy_project:
          path: "client-side-rendering/vue-instantsearch"
          app_name: "is-seo-csr-vue-0"

workflows:
  version: 2.1
  build:
    jobs:
      - build_dynamic_rendering
      - deploy_dynamic_rendering:
          requires:
            - build_dynamic_rendering
          filters:
            branches:
              only: master
      - build_server_side_rendering
      - deploy_server_side_rendering:
          requires:
            - build_server_side_rendering
          filters:
            branches:
              only: master
      - build_partial_server_side_rendering
      - deploy_partial_server_side_rendering:
          requires:
            - build_partial_server_side_rendering
          filters:
            branches:
              only: master
      - build_client_side_rendering_js
      - deploy_client_side_rendering_js:
          requires:
            - build_client_side_rendering_js
          filters:
            branches:
              only: master
      - build_client_side_rendering_react
      - deploy_client_side_rendering_react:
          requires:
            - build_client_side_rendering_react
          filters:
            branches:
              only: master
      - build_client_side_rendering_angular
      - deploy_client_side_rendering_angular:
          requires:
            - build_client_side_rendering_angular
          filters:
            branches:
              only: master
      - build_client_side_rendering_vue
      - deploy_client_side_rendering_vue:
          requires:
            - build_client_side_rendering_vue
          filters:
            branches:
              only: master

