version: 2.1

executors:
  node9:
    docker:
      - image: circleci/node:9

commands:
  build_project:
    description: "Building << path >>..."
    parameters:
      path:
        type: string
        default: ""
    steps:
      - run:
          name: "Building << parameters.path >>"
          command: |
            cd "<< parameters.path >>"
            yarn
            yarn build
      - run:
          name: "Deploying << parameters.path >>"
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/is-seo-dynamic-routing-0.git master
jobs:
  build_dynamic_rendering:
    executor: node9
    steps:
      - checkout
      - build_project:
           path: "dynamic-rendering/instantsearch.js"

workflows:
  version: 2.1
  build:
    jobs:
      - build_dynamic_rendering
